Ruby_on_rails_api/config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # With api as subdomain ex: api.localhost/users
  namespace :api, defaults: {format: :json},
            constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, :stories, :tags
      post :token, controller: 'base'
    end
  end

  # With api as first parameter ex: localhost:3000/api/users
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, :stories, :tags
      post :token, controller: 'base'
    end
  end

  resources :stories
  resources :users
  resources :domains, except: [:edit, :update]

  root 'sessions#new'

end

Ruby_on_rails_api/app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sharing is caring", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "All stories", stories_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Add Domain", new_domain_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li><%= link_to "Your Domains", domain_path(current_user) %></li>
                    <% if current_user.admin? %>
                      <li><%= link_to "All Domains", domains_path %></li>
                    <% end %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete", data: {no_turbolink: true} %>
                  </li>
                </ul>
              </li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

Ruby_on_rails_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>