Ruby_on_rails_api/config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # With api as subdomain ex: api.localhost/users
  namespace :api, defaults: {format: :json},
            constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, :stories, :tags
      post :token, controller: 'base'
    end
  end

  # With api as first parameter ex: localhost:3000/api/users
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, :stories, :tags
      post :token, controller: 'base'
    end
  end

  resources :stories
  resources :users
  resources :domains, except: [:edit, :update]

  root 'sessions#new'

end

Ruby_on_rails_api/app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  belongs_to :creator
  has_many :story_tags, dependent: :destroy
  has_many :tags, through: :story_tags

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  
  validates :title,
            :presence => {:message => "You have to give a title"},
             length: { maximum: 50 }
            
  validates :description,
            :presence => {:message => "You have to give a description"},
             length: { maximum: 200 }

  # fetch coordinates from address if it is present.
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  # search for stories by title or description if present
  def self.search(params)
    story = order('created_at DESC') # note: default is all, just sorted
    story = where('title LIKE ? OR description LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    story
  end

  ###################################################
  ## Code bellow is not for the API, view specific ##
  ###################################################

  # Insert each tag in db separated with comma.
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
  # Render all the tags separated by commas.
  def all_tags
    self.tags.map(&:name).join(", ")
  end

end

Ruby_on_rails_api/app/controllers/api/v1/stories_controller.rb
class Api::V1::StoriesController < Api::V1::BaseController

  before_action :authenticate_creator!, only: [:create, :destroy, :update]

  def index
    if params[:tag].present? # Find by tags
      @stories = Tag.find_by_name(params[:tag]).stories.limit(@limit).offset(@offset)
    elsif params[:location].present? # Find by location
      @stories = Story.near(params[:location], params[:range] ||= 50).limit(@limit).offset(@offset)
    else # Find by search string by title and description. If search is empty it renders all
      @stories = Story.search(params).limit(@limit).offset(@offset)
    end

  end

  def show
    @story = Story.find(params[:id])
  end

  def create
    #abort current_user.inspect
    authorize current_user # check policies/user_policy.rb for auth rules

    story = current_user.stories.new(story_params.except(:tags))

    # add the id from developers api key to know which domain the story belongs to
    story.user_id = @developer.id

    # if tags are present
    if story_params[:tags]
        story_params[:tags].each do |tag|
        # If tag exists then use existing tag name
        if Tag.exists?(tag)
          story.tags << Tag.find_by_name(tag["name"])
        else
          story.tags << Tag.new(tag)
        end
      end
    end

    if story.save
      response_with('Story successfully created', 200)
    else
      response_with('Sorry, could not create story', 400)
    end
  end

  # update story and add new tags if present
  def update
     story = Story.find(params[:id])
     authorize story # check policies/story_policy.rb for auth rules

      if story_params[:tags]
        story_params[:tags].each do |tag|
          # If tag exists then use existing tag name
          if Tag.exists?(tag)
            story.tags << Tag.find_by_name(tag["name"])
          else
            story.tags << Tag.new(tag)
          end
        end
      end

      if story.update(story_params.except(:tags)) && story.save
        response_with('Story successfully saved', 200)
      else
        response_with('Could not update story', 400)
      end
  end

  def destroy
    story = Story.find(params[:id])
    authorize story # check policies/story_policy.rb for auth rules

    if story.destroy
      response_with('Story successfully removed', 200)
    else
      response_with('Could not find story', 404)
    end
  end

  private

  def story_params
    params.require(:story).permit(:title, :description, :address, :longitude, :latitude, tags: [ :name ])
  end

end

Ruby_on_rails_api/app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :logged_in_user, except: :index
    before_action :correct_user,   only: :destroy

    def index
      @stories = Story.all
    end
    
    def show
      @story = Story.find(params[:id])
    end
    
    def new
      @story = Story.new
    end
    
    def create
      @story = current_user.stories.build(story_params)
      
      if @story.save
        flash[:success] = "Stories successfully created"
        redirect_to stories_path
      else
        render "new"
      end
    end
    
    def edit
      @story = Story.find(params[:id])
    end
    
    def update
      @story = Story.find(params[:id])
      if @story.update(story_params)
        flash[:success] = "Story successfully updated"
        redirect_to @story
      else
       render "edit"
      end
    end
    
    def destroy
      @story.destroy
      flash[:success] = "Story successfully removed"
      redirect_to(:back)
    end
    
    private

    def story_params
      params.require(:story).permit(:title, :description, :all_tags, :address, :longitude, :latitude)
    end

    def correct_user
      @story = current_user.stories.find_by(id: params[:id])
      redirect_to stories_path if @story.nil?
    end

end

Ruby_on_rails_api/app/helpers/stories_helper.rb
module StoriesHelper
end

Ruby_on_rails_api/app/views/stories/_story.html.erb
<li id="stories-<%= story.id %>">
  <h3><%= story.title %></h3>
  <p><%= story.description %></p>
  <div class="tags">
    <%=raw story.all_tags %>
  </div>
    <% if logged_in? %>
      <% if current_user.admin? || current_user?(@user) %>
        <p><%= link_to "Edit", edit_story_path(story) %> |
         <%= link_to "Delete", story, :data => {:confirm => "Are you sure?"}, :method => :delete %>
        </p>
      <% end %>
    <% end %>
  

  <span>
    Posted <%= time_ago_in_words(story.created_at) %> ago.
  </span>
</li>

Ruby_on_rails_api/app/views/stories/edit.html.erb
<h1>Edit story</h1>

<%= form_for @story do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="text_field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="text_area">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="text_field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="text_field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="text_field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>
  <div class="tag_field">
    <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
  </div>

  <div class="submit">
    <%= f.submit "Update" %>
  </div>
  
  <% end %>

Ruby_on_rails_api/app/views/stories/index.html.erb
<% provide(:title, "Story list") %>

<h1>My stories</h1>

<% @stories.each do |story| %>
  <h2><%= link_to story.title, story %></h2>
<% end %>

<%= link_to "create new story", new_story_path %>

Ruby_on_rails_api/app/views/stories/new.html.erb
<h1>Create new story</h1>

<%= form_for @story do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="text_field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="text_area">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="text_field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="text_field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="text_field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>
  <div class="tag_field">
    <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
  </div>

  <div class="submit">
    <%= f.submit "submit" %>
  </div>
  
  <% end %>

Ruby_on_rails_api/app/views/stories/show.html.erb
<% provide(:title, "Story") %>

<h1><%= @story.title%></h1>
<p><%= @story.description%></p>
<p>Longitude: <%= @story.longitude%></p>
<p>Latitude: <%= @story.latitude%></p>

Posted <%= time_ago_in_words(@story.created_at) %> ago

<% if @story.created_at != @story.updated_at %>
/ Updated <%= time_ago_in_words(@story.updated_at) %> ago
<% end %>